m31-vendor: Add missing hardware/samsung
error: vendor/samsung/m31/Android.bp:139:1: "libbauthtzcommon" depends on undefined module "libteecl".

Signed-off-by: FelcoX <parbindarsingh@outlook.com>